# -*- coding: utf-8 -*-
"""cover-letter-template-convert.ipynb

Automatically generated by Colaboratory.

"""

import importlib.util
import sys

import random
import datetime
import matplotlib.pyplot as plt
import argparse
from pathlib import Path

from docx.shared import Cm
from docxtpl import DocxTemplate, InlineImage
from docx.shared import Cm, Inches, Mm, Emu
from docx2pdf import convert

def parse_args():
    parser = argparse.ArgumentParser()

    ## Arguments to be used to fill in context for template
    parser.add_argument('--company', type=str, default='Apple')
    parser.add_argument('--role', type=str, default='Data Scientist')

    ## Arguments to be used for generating template
    parser.add_argument('--name', type=str, default='Sunny Son')
    parser.add_argument('--template', type=str, default='Cover-Letter-Template.docx')
    parser.add_argument('--folder', type=str, default=None)
    parser.add_argument('--pdf', type=bool, default=True)

    return parser.parse_args()

def get_today():
    today = datetime.date.today()
    return today.strftime('%B %d, %Y')

if __name__ == '__main__':
    args = parse_args()
    date = get_today()

    template = DocxTemplate(args.template)

    context = {
        'COMPANY': args.company,
        'ROLE': args.role,
        'DATE': date
    }

    template.render(context)

    out_name = f'{args.name}-{args.company}-{args.role}-Cover-Letter.docx'

    if not args.pdf:
        template.save(out_name)

    else:
        if not args.folder:
            convert(template, out_name)
        else:
            out_folder = Path(f'./{args.folder}/').mkdir(parents=True, exist_ok=True)
            out_dir = str(out_folder) + out_name
            convert(template, out_dir)
